# Ejemplos

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

    {"nombre": "Pepino", "stock": 47, "descripcion": "Descripcion del pepino" },
    {"nombre": "Patata", "stock": 20, "descripcion": "Tuberculo que se puede comer de varias formas"},
    {"nombre": "Lechuga", "stock": 4, "descripcion": "Vegetal de hojas verdes para ensaladas"},
    {"nombre": "Calabaza", "stock": 7, "descripcion": "Producto vegetal cuyo valor se incrementa a finales de Octubre"},
    {"nombre": "Cebolla", "stock": 52, "descripcion": "Bulbo que te hará llorar al trocearlo"},
    {"nombre": "Tomate", "stock": 19, "descripcion": "De hecho, este producto es una fruta, no una verdura"},
    {"nombre": "Berenjena", "stock": 31, "descripcion": "No confundir con un huevo"},
    {"nombre": "Sandia", "stock": 11, "descripcion": "No usar para pintar paredes de rojo"},
    {"nombre": "Brocoli", "stock": 73, "descripcion": "El mas pequeño de los arboles"},
    {"nombre": "Calabacin", "stock": 44, "descripcion": "No, no es una calabaza pequeña"},
    {"nombre": "Pimenton", "stock": 13, "descripcion": "Un precioso pimiento listo para ser brutalmente convertido en polvo"}

### 

POST http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Melocoton", 
    "stock": 20,
    "descripcion": "Descripcion del melocoton" 
}


### 

GET http://localhost:3000/api/productos HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jamon", 
    "stock": 47,
    "descripcion": "Descripcion del jamon" 
}

###

DELETE http://localhost:3000/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

### Posts

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pepino", 
    "stock": 47,
    "descripcion": "Descripcion del pepino" 
}

###

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Soy un producto nuevo", 
    "stock": 47,
    "descripcion": "Descripcion del producto nuevo" 
}

### Visualizar todo

GET  https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json