# Ejemplos

POST https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{
        "nombre": "Patata", 
        "stock": 20, 
        "descripcion": "Tuberculo que se puede comer de varias formas"
}

### 

POST https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Melocoton", 
    "stock": 20,
    "descripcion": "Descripcion del melocoton" 
}


### 

GET https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

###

GET https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

###

PUT https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jamon", 
    "stock": 47,
    "descripcion": "Descripcion del jamon" 
}

###

DELETE https://api-mongodb-dev-jfpj.1.ie-1.fl0.io/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/productos/65539b4ef00527807b5e4b13 HTTP/1.1
content-type: application/json

### Posts

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pepino", 
    "stock": 47,
    "descripcion": "Descripcion del pepino" 
}

###

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Soy un producto nuevo", 
    "stock": 47,
    "descripcion": "Descripcion del producto nuevo" 
}

### Visualizar todo

GET  https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json