# Ejemplos

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pepino", 
    "stock": 47,
    "descripcion": "Descripcion del pepino" 
}

### 

POST http://localhost:3000/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Melocoton", 
    "stock": 20,
    "descripcion": "Descripcion del melocoton" 
}


### 

GET http://localhost:3000/api/users HTTP/1.1
content-type: application/json

###

GET http://localhost:3000/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/api/users/6548f6566802ae8e19bd782b HTTP/1.1
content-type: application/json

{ 
    "nombre": "Jamon", 
    "stock": 47,
    "descripcion": "Descripcion del jamon" 
}

###

DELETE http://localhost:3000/api/users/6544e7ced958fc237ad628ed HTTP/1.1
content-type: application/json

###

DELETE https://api-mongodb-dev-nnas.3.us-1.fl0.io/api/users/6542da20c20d9ad95c739701 HTTP/1.1
content-type: application/json

### Posts

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/users HTTP/1.1
content-type: application/json

{ 
    "nombre": "Pepino", 
    "stock": 47,
    "descripcion": "Descripcion del pepino" 
}

###

POST https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json

{ 
    "nombre": "Soy un producto nuevo", 
    "stock": 47,
    "descripcion": "Descripcion del producto nuevo" 
}

### Visualizar todo

GET  https://api-mongodb-dev-reda.2.us-1.fl0.io/api/productos HTTP/1.1
content-type: application/json